name = "my-worker"  # Your project name
type = "javascript"  # The type of your project, typically 'javascript' or 'webpack'

[build]  # Optional build configuration
command = "npm install"  # Command to run before build (if needed)
cwd = "."  # The working directory for the build command
watch_dir = "."  # Directory to watch for file changes during development

[env.production]  # Configuration for the production environment
name = "my-worker-prod"
account_id = "your-cloudflare-account-id"
workers_dev = true  # Use Cloudflare's workers.dev subdomain
compatibility_date = "2024-01-01"

[[kv_namespaces]]  # Bind Cloudflare KV namespaces to your Worker
binding = "MY_KV_NAMESPACE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-id"  # (Optional, for preview environments)

[[routes]]  # Define routes where the Worker will respond
pattern = "example.com/*"
zone_id = "your-zone-id"
